enum StatusCodes {
  // SUCCESS
  SUCCESS_CODE = 1000,

  // FAIL
  FAIL_CODE_UNKNOWN = 2000,
  FAIL_CODE_BAD_REQUEST,
  FAIL_CODE_MISSING_HEADER,
  FAIL_CODE_BAD_ROUTE,
  FAIL_CODE_BAD_REQUEST_METHOD,
  FAIL_CODE_BAD_REQUEST_BODY,
  FAIL_CODE_ROUTE_VALIDATION,
  FAIL_CODE_ROUTE_VALIDATION_SET_FRONTEND_NOT_USED,
  FAIL_CODE_ROUTE_VALIDATION_MISSING,
  FAIL_CODE_BODY_VALIDATION,
  FAIL_CODE_USER_PERMISSION_MISSING,

  // DATABASE 2050
  FAIL_CODE_DATABASE_CONNECTION = 2050,
  FAIL_CODE_DATABASE_QUERY,
  FAIL_CODE_DATABASE_INVALID_ASSOCIATION,
  FAIL_CODE_DATABASE_UNEDITABLE_FIELD,

  // SIGN_IN 2100
  FAIL_CODE_SIGN_IN = 2100,

  // USER 2200
  FAIL_CODE_USER_UNKNOWN = 2200,
  FAIL_CODE_USER_NOT_FOUND,
  FAIL_CODE_USER_CREATION,
  FAIL_CODE_USER_UPDATE,
  FAIL_CODE_USER_UNAUTHORIZED,
}

export default StatusCodes;
